### ISSUE TITLE
Crash: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by Prodromos-alt-f4** [DestinyItemManager/DIM#10101]
### DIM Version

Version 7.93.0 (release), built on 06/11/2023, 02:56:53

### Browser Details

Version 119.0.6045.124 (Official Build) (64-bit)

### OS Details

Windows 10 

### Describe the bug

After I make a search with the filter: "stat:total:<=60" the page goes blank. 
There is an exception not being caught. in the log I think I found where the problem is but I haven't checked the code itself. 
Let me know if you fix it I am curious how. 

### Logs

```shell
col:214898
line:2
message:"Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."
source:"https://app.destinyitemmanager.com/240-c5c2c450.js"

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ml (https://app.destinyitemmanager.com/240-c5c2c450.js:2:263087)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264341)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:265919)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:265919)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264801)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264739)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
    at yl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264604)
    at vl (https://app.destinyitemmanager.com/240-c5c2c450.js:2:264491)
```

**Comment by robojumper** [comment]
What browser are you using? Are you using any browser extensions that could mess with DIM, such as Clarity? What happens in a different browser / on a different device?

**Comment by bhollis** [comment]
We see this occasionally in Sentry but it's unclear why. Do you have any extensions enabled?

**Comment by Prodromos-alt-f4** [comment]
I do but I don't think they would interfere.
The only one would be the translation extension.
But it translates to English which is the language it already is so it
should not kick in.

**Comment by bhollis** [comment]
Definitely try without that
