### ISSUE TITLE
Error looking up emblem metric information

### ISSUE THREAD

**Issue by TheIcicle** [DestinyItemManager/DIM#10126]
### DIM Version

Version 7.95.0 (release), built on 20/11/2023, 12:59:00 pm

### Browser Details

Firefox 119.0

### OS Details

Windows 10

### Describe the bug

Clicking on emblem in the 6th slot in the inventory results in an error message stating "I.PresentationNode.get(...) is undefined"
Issue can be reproducted on Edge (Edge 119.0.0.0) however results in the error message "Cannot read properties of undefined (reading 'displayProperties')
![DIMEmblem](https://github.com/DestinyItemManager/DIM/assets/28527338/783d9241-d05d-4542-90eb-9bc8e14e876e)

Edge:
![DimEdge](https://github.com/DestinyItemManager/DIM/assets/28527338/ed28c8e8-0495-480a-9225-5f442d169bab)
FF:
![DimFF](https://github.com/DestinyItemManager/DIM/assets/28527338/d829717a-252e-4758-8822-d412296d9ed8)

Cannot navigate to other sub menus (eg. Inventory, vendors, progress, etc) unless a full page reload is done.

### Logs

```shell
EDGE LOGS-

[app] DIM v7.95.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:145 Language Detected: en
instrument.ts:145 Language Assigned: en
instrument.ts:145 [d2-stores] Loaded cached profile from IndexedDB
instrument.ts:145 [dim sync] globalSettings Object
www.google-analytics.com/analytics.js:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
inventory:1  Tracking Prevention blocked a Script resource from loading https://www.google-analytics.com/analytics.js.
log.ts:58 Load manifest: 6586.80810546875 ms
log.ts:58 Process inventory: 128.84619140625 ms
log.ts:58 Inventory state update: 17.97216796875 ms
inventory:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
instrument.ts:145  [d2-stores] Cached profile is older than Bungie.net cache time, proceeding. 351540
(anonymous) @ instrument.ts:145
instrument.ts:145 [dim sync] Saving profile data to IDB
instrument.ts:145 [d2-stores] Profile from Bungie.net was newer than cached profile, using it. 304269 304269 Thu Nov 23 2023 10:37:11 GMT+1100 (Australian Eastern Daylight Time) Thu Nov 23 2023 10:32:06 GMT+1100 (Australian Eastern Daylight Time)
log.ts:58 Process inventory: 56.011962890625 ms
log.ts:58 Inventory state update: 21.0849609375 ms
instrument.ts:145  TypeError: Cannot read properties of undefined (reading 'displayProperties')
    at l (MetricBanner.tsx:26:75)
    at Ca (react-dom.production.min.js:167:137)
    at Cl (react-dom.production.min.js:290:337)
    at xu (react-dom.production.min.js:280:389)
    at bu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at su (react-dom.production.min.js:271:88)
    at cu (react-dom.production.min.js:273:300)
    at Ui (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:145
instrument.ts:145  [DIM Code] TypeError: Cannot read properties of undefined (reading 'displayProperties')
    at l (MetricBanner.tsx:26:75)
    at Ca (react-dom.production.min.js:167:137)
    at Cl (react-dom.production.min.js:290:337)
    at xu (react-dom.production.min.js:280:389)
    at bu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at su (react-dom.production.min.js:271:88)
    at cu (react-dom.production.min.js:273:300)
    at Ui (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object





FIREFOX LOGS - 

Some cookies are misusing the recommended “SameSite“ attribute 6
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 111
Some cookies are misusing the recommended “SameSite“ attribute 4
Some cookies are misusing the recommended “SameSite“ attribute 250
Some cookies are misusing the recommended “SameSite“ attribute 130
Some cookies are misusing the recommended “SameSite“ attribute 250
```

**Comment by robojumper** [comment]
Hm, I guess these emblems have orphaned metrics equipped that you can't even equip in game anymore because they've been detached from the relevant PresentationNodes, likely one of these:

![grafik](https://github.com/DestinyItemManager/DIM/assets/14299449/24c9f74b-2b43-4001-8e57-94ab84129449)
