### ISSUE TITLE
I broke something trying to delete a saved search

### ISSUE THREAD

**Issue by Chippy569** [DestinyItemManager/DIM#10809]
### DIM Version

Version 8.47.1.3665 (beta), built on 11/20/2024, 1:44:21 PM

### Browser Details

Chrome 131.0.0.0

### OS Details

Windows 10 Debug

### Describe the bug

![Screenshot 2024-11-23 224453](https://github.com/user-attachments/assets/246cd286-8c38-4af7-9516-a1018dfeb127)

I tried to delete a (very old, unused) favorited search, but I'm thinking this one maybe was too long or something and it's now permanently broken something in my account. The "Failed to save data to DIM Sync" error will show up once, but the smaller "DIM Sync Save Error" will constantly spawn and does not automatically hide itself, so after ~5 minutes there's so many instances of the sync save error that it's faster to reload the page than to try to click the errors away. This means a bunch of the right side of my inventory is inaccessible until I do so.

Same error occurs if I open the "normal" DIM rather than the "beta" DIM.

### Logs

```shell
console.ts:40 [app] DIM v8.47.1.3665 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.38.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
console.ts:40 ⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath.
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 [dim sync] globalSettings Object
console.ts:40 [dim sync] Flushing queue of 36 updates
console.ts:40 [d2-stores] Loaded cached profile from IndexedDB, using it until new data is available. It is 222.932s old.
inventory:1 Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.
console.ts:40 [dim sync] Saving profile data to IDB
console.ts:40 [dim sync] save_search InvalidArgument "tmmania's vault analyzer end-game edition | highlights trash | keeps top 2.5% armor | update version: july 5th, 2021" or (((is:weapon (is:sunset or is:blue)) or (is:armor -is:exotic -is:classitem -(source:raid -is:dupelower -source:dcv) -maxbasestatvalue:any -basestat:any:>=23 -basestat:total:>=65 -(basestat:mobility&resilience:>=19 or basestat:mobility&recovery:>=19 or basestat:mobility&discipline:>=19 or basestat:mobility&intellect:>=19 or basestat:mobility&strength:>=19 or basestat:resilience&recovery:>=19 or basestat:resilience&discipline:>=19 or basestat:resilience&intellect:>=19 or basestat:resilience&strength:>=19 or basestat:recovery&discipline:>=19 or basestat:recovery&intellect:>=19 or basestat:recovery&strength:>=19 or basestat:discipline&intellect:>=19 or basestat:discipline&strength:>=19 or basestat:intellect&strength:>=19) -(basestat:mobility&resilience&recovery:>=16.66 or basestat:mobility&resilience&discipline:>=16.66 or basestat:mobility&resilience&intellect:>=16.66 or basestat:mobility&resilience&strength:>=16.66 or basestat:mobility&recovery&discipline:>=16.66 or basestat:mobility&recovery&intellect:>=16.66 or basestat:mobility&recovery&strength:>=16.66 or basestat:mobility&discipline&intellect:>=16.66 or basestat:mobility&discipline&strength:>=16.66 or basestat:mobility&intellect&strength:>=16.66 or basestat:resilience&recovery&discipline:>=16.66 or basestat:resilience&recovery&intellect:>=16.66 or basestat:resilience&recovery&strength:>=16.66 or basestat:resilience&discipline&intellect:>=16.66 or basestat:resilience&discipline&strength:>=16.66 or basestat:resilience&intellect&strength:>=16.66 or basestat:recovery&discipline&intellect:>=16.66 or basestat:recovery&discipline&strength:>=16.66 or basestat:recovery&intellect&strength:>=16.66 or basestat:discipline&intellect&strength:>=16.66) -(basestat:mobility&resilience&recovery&intellect:>=14.25 or basestat:mobility&resilience&recovery&discipline:>=14.25 or basestat:mobility&resilience&recovery&strength:>=14.25 or basestat:mobility&resilience&intellect&discipline:>=14.25 or basestat:mobility&resilience&intellect&strength:>=14.25 or basestat:mobility&resilience&discipline&strength:>=14.25 or basestat:mobility&recovery&intellect&discipline:>=14.25 or basestat:mobility&recovery&intellect&strength:>=14.25 or basestat:mobility&recovery&discipline&strength:>=14.25 or basestat:mobility&intellect&discipline&strength:>=14.25 or basestat:resilience&recovery&intellect&discipline:>=14.25 or basestat:resilience&recovery&intellect&strength:>=14.25 or basestat:resilience&recovery&discipline&strength:>=14.25 or basestat:resilience&intellect&discipline&strength:>=14.25 or basestat:recovery&intellect&discipline&strength:>=14.25) -(basestat:mobility&resilience&recovery&discipline&intellect&strength:>=9 basestat:sixthhighest:>5 basestat:highest:<16)) or (is:classitem energycapacity:<=5 -is:modded -is:locked -(source:raid -is:dupelower -source:dcv)) or (is:armor is:sunset) or (is:armor is:blue -(name:"war mantis" is:gauntlets)) or ((is:armor or is:weapon) (is:common or is:uncommon))) -(is:tagged -tag:junk) -is:maxpower -power:pinnaclecap -is:inloadout -is:masterwork -(is:armor -is:armor2.0) -(is:armor source:events)) or (tag:junk -is:maxpower) Search query must be under 2048 characters Object
(anonymous) @ console.ts:40Understand this errorAI
console.ts:40 [dim sync] Unable to save updates to DIM API TypeError: Cannot destructure property 'query' of 't.payload' as it is undefined.
    at V (reducer.ts:1420:15)
    at q (reducer.ts:1445:7)
    at reducer.ts:881:41
    at produce (immer.mjs:571:20)
    at reducer.ts:881:15
    at N (reducer.ts:323:14)
    at reducers.ts:40:23
    at v (redux.mjs:160:22)
    at redux-thunk.mjs:7:12
    at observerMiddleware.ts:91:20
    at dispatch (redux.mjs:371:38)
    at actions.ts:346:7
    at async actions.ts:224:9
(anonymous) @ console.ts:40Understand this errorAI
console.ts:40 [dim sync] Waiting 18804.857989435186 ms before re-attempting updates
log.ts:59 [manifest] Load manifest: 2881.05517578125 ms
log.ts:59 [d2-stores] Process inventory: 131.572998046875 ms
log.ts:59 [d2-stores] Inventory state update: 13.468994140625 ms
log.ts:11 [d2-stores] Profile from Bungie.net is is 5.153s old, while the cached profile is 233.726s old. Using the new profile from Bungie.net.
log.ts:59 [d2-stores] Process inventory: 83.998046875 ms
log.ts:59 [d2-stores] Inventory state update: 26.385009765625 ms
```

**Comment by Chippy569** [comment]
![Screenshot 2024-11-23 232748](https://github.com/user-attachments/assets/2de90590-8fd4-46dd-bcbe-56454fe4f400)
once it's in this state, it's faster and easier to refresh than to try to clear all the notifications.

**Comment by bhollis** [comment]
Thanks, I see the problem. Should have a fix this afternoon.

**Comment by Chippy569** [comment]
> Thanks, I see the problem. Should have a fix this afternoon.

Hey, just wanted to update you -- bug is still present.

![Screenshot 2024-11-26 202708](https://github.com/user-attachments/assets/f7e34e65-1616-4999-9c80-608265ed3903)
![Screenshot 2024-11-26 202650](https://github.com/user-attachments/assets/f19f157f-519d-4502-a662-cdc207132bff)

**Comment by bhollis** [comment]
Yep the fix hasn't been merged, so that's expected

**Comment by bhollis** [comment]
This should be fixed on Beta now. It'll roll out to app on Sunday.
