### ISSUE TITLE
Saved searches are randomly unsaved

### ISSUE THREAD

**Issue by drkrthnblck** [DestinyItemManager/DIM#10849]
### DIM Version

Version 8.51.0 (release), built on 12/15/2024, 9:39:31 PM

### Browser Details

Chrome 131.0.0.0 - Windows 10

### OS Details

Windows 11

### Describe the bug

This has only happened in the past couple of days or so, but my saved searches are randomly being deleted. There isn't a keyboard shortcut for this, so I'm genuinely perplexed as to why this is happening.

I can't seem to reproduce it, and leaving the saved search up or closing it makes no difference—it just seems to happen at any time for no reason at all. The only indication that it's happening is a shrinking list of saved searches.

### Logs

```shell
content.js:79 Unrecognized Content-Security-Policy directive 'prefetch-src'.
(anonymous) @ content.js:79Understand this errorAI
console.ts:40 [app] DIM v8.51.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
VM74:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://opencollective.com". Either the 'unsafe-inline' keyword, a hash ('sha256-I4JHHin+mKGzylrcnIe9l5utTh2aKt8q7xAT0YAftBg='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ VM74:1Understand this errorAI
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89Understand this errorAI
console.ts:40 [dim sync] globalSettings Object
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
content_script.js:66 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at wasDragged (content_script.js:66:52)
    at HTMLAnchorElement.onMouseUp (content_script.js:112:13)Understand this errorAI
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
VM74:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://opencollective.com". Either the 'unsafe-inline' keyword, a hash ('sha256-I4JHHin+mKGzylrcnIe9l5utTh2aKt8q7xAT0YAftBg='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ VM74:1Understand this errorAI
console.ts:40 [d2-stores] Loaded cached profile from IndexedDB, using it until new data is available. It is 70.811s old.
log.ts:59 [manifest] Load manifest: 1147.98095703125 ms
log.ts:59 [d2-stores] Process inventory: 50.52001953125 ms
log.ts:59 [d2-stores] Inventory state update: 7.47216796875 ms
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89Understand this errorAI
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
VM74:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://opencollective.com". Either the 'unsafe-inline' keyword, a hash ('sha256-I4JHHin+mKGzylrcnIe9l5utTh2aKt8q7xAT0YAftBg='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ VM74:1Understand this errorAI
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
console.ts:40 [d2-stores] Profile from Bungie.net is is 31.405s old, while the cached profile is 76.433s old. Using the new profile from Bungie.net.
log.ts:59 [d2-stores] Process inventory: 53.04296875 ms
log.ts:59 [d2-stores] Inventory state update: 103.440185546875 ms
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
VM74:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googletagmanager.com https://*.google-analytics.com https://opencollective.com". Either the 'unsafe-inline' keyword, a hash ('sha256-I4JHHin+mKGzylrcnIe9l5utTh2aKt8q7xAT0YAftBg='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ VM74:1Understand this errorAI
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
_flushOutcomes @ baseclient.ts:912
(anonymous) @ client.ts:87Understand this errorAI
```

**Comment by bhollis** [comment]
Thanks, I think I have an idea of what might be happening.

**Comment by bhollis** [comment]
Should be fixed now.
