### ISSUE TITLE
"No wish list information found."

### ISSUE THREAD

**Issue by The-Dreamz** [DestinyItemManager/DIM#10843]
### DIM Version

Version 8.50.1 (release), built on 12/12/2024, 8:18:36 PM

### Browser Details

Edge 131.0.0.0 - Windows 10 Debug

### OS Details

Windows 11

### Describe the bug

After adding another custom wish list from github, it started to tell me, "No wish list information found." in the top right. 

I've never had this issue before and I've tried removing to re-add wish lists that have worked up until two days ago and it won't add them - and yes, the link(s) are correct. However, now when I try to remove Voltron (for example), it won't remove and it'll just hit me with that pop up in the top right.

The weird thing is - I'm still getting thumbs up on rolls that I know are in the wish lists already on there. 

### Logs

```shell
https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
sendSession @ baseclient.ts:366
captureSession @ baseclient.ts:230
g @ exports.ts:340
h @ exports.ts:319
f @ exports.ts:296
(anonymous) @ sdk.ts:328
l @ handlers.ts:58
(anonymous) @ history.ts:56
push @ chunk-7R3XDUXW.mjs:280
(anonymous) @ chunk-7R3XDUXW.mjs:4150
(anonymous) @ chunk-7R3XDUXW.mjs:7429
(anonymous) @ chunk-7R3XDUXW.mjs:7202
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:55
Fr @ react-dom.production.min.js:105
Vr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cu @ react-dom.production.min.js:273
Ie @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Yt @ react-dom.production.min.js:74
Kt @ react-dom.production.min.js:73
r @ helpers.ts:104Understand this errorAI
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
sendSession @ baseclient.ts:366
captureSession @ baseclient.ts:230
g @ exports.ts:340
m @ exports.ts:358
(anonymous) @ sdk.ts:329
l @ handlers.ts:58
(anonymous) @ history.ts:56
push @ chunk-7R3XDUXW.mjs:280
(anonymous) @ chunk-7R3XDUXW.mjs:4150
(anonymous) @ chunk-7R3XDUXW.mjs:7429
(anonymous) @ chunk-7R3XDUXW.mjs:7202
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:55
Fr @ react-dom.production.min.js:105
Vr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cu @ react-dom.production.min.js:273
Ie @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Yt @ react-dom.production.min.js:74
Kt @ react-dom.production.min.js:73
r @ helpers.ts:104Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Update.txt?token=GHSAT0AAAAAAC3ZHTKYDJIXHGUFCESJINTSZ22CJ5A 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ Destiny.tsx:113
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Wish%20List%20-%20Newest.txt?token=GHSAT0AAAAAAC3ZHTKZXEVM4WQZI5DWCKD4Z22CM4A 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ Destiny.tsx:113
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Wish%20List%20-%20Newest.txt?token=GHSAT0AAAAAAC3ZHTKZMDVBEUF4R7P2WIMQZ22COPA 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ Destiny.tsx:113
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
log.ts:47 [wishlist] Unable to load wish list s: 404: Not Found
    at i (https://app.destinyitemmanager.com/747-fa3197e0.js:1:1206)
    at async https://app.destinyitemmanager.com/main-8aed2545.js:1:780278
    at async Promise.all (index 1)
    at async https://app.destinyitemmanager.com/main-8aed2545.js:1:780183
(anonymous) @ console.ts:40
i @ log.ts:47
(anonymous) @ wishlist-fetch.ts:96
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ Destiny.tsx:113
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
sendSession @ baseclient.ts:366
captureSession @ baseclient.ts:230
g @ exports.ts:340
h @ exports.ts:319
f @ exports.ts:296
(anonymous) @ sdk.ts:328
l @ handlers.ts:58
(anonymous) @ history.ts:56
push @ chunk-7R3XDUXW.mjs:280
(anonymous) @ chunk-7R3XDUXW.mjs:4150
(anonymous) @ chunk-7R3XDUXW.mjs:7429
(anonymous) @ chunk-7R3XDUXW.mjs:7202
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:55
Fr @ react-dom.production.min.js:105
Vr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cu @ react-dom.production.min.js:273
Ie @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Yt @ react-dom.production.min.js:74
Kt @ react-dom.production.min.js:73
r @ helpers.ts:104Understand this errorAI
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
sendSession @ baseclient.ts:366
captureSession @ baseclient.ts:230
g @ exports.ts:340
m @ exports.ts:358
(anonymous) @ sdk.ts:329
l @ handlers.ts:58
(anonymous) @ history.ts:56
push @ chunk-7R3XDUXW.mjs:280
(anonymous) @ chunk-7R3XDUXW.mjs:4150
(anonymous) @ chunk-7R3XDUXW.mjs:7429
(anonymous) @ chunk-7R3XDUXW.mjs:7202
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:55
Fr @ react-dom.production.min.js:105
Vr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cu @ react-dom.production.min.js:273
Ie @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Yt @ react-dom.production.min.js:74
Kt @ react-dom.production.min.js:73
r @ helpers.ts:104Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Update.txt?token=GHSAT0AAAAAAC3ZHTKYDJIXHGUFCESJINTSZ22CJ5A 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ WishListSettings.tsx:32
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Wish%20List%20-%20Newest.txt?token=GHSAT0AAAAAAC3ZHTKZXEVM4WQZI5DWCKD4Z22CM4A 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ WishListSettings.tsx:32
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
wishlist-fetch.ts:78 
        
        
       GET https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Wish%20List%20-%20Newest.txt?token=GHSAT0AAAAAAC3ZHTKZMDVBEUF4R7P2WIMQZ22COPA 404 (Not Found)
(anonymous) @ fetch.ts:78
(anonymous) @ wishlist-fetch.ts:78
(anonymous) @ wishlist-fetch.ts:77
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ WishListSettings.tsx:32
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
log.ts:47 [wishlist] Unable to load wish list s: 404: Not Found
    at i (https://app.destinyitemmanager.com/747-fa3197e0.js:1:1206)
    at async https://app.destinyitemmanager.com/main-8aed2545.js:1:780278
    at async Promise.all (index 1)
    at async https://app.destinyitemmanager.com/main-8aed2545.js:1:780183
(anonymous) @ console.ts:40
i @ log.ts:47
(anonymous) @ wishlist-fetch.ts:96
await in (anonymous)
(anonymous) @ redux-thunk.mjs:5
(anonymous) @ observerMiddleware.ts:62
(anonymous) @ WishListSettings.tsx:32
il @ react-dom.production.min.js:243
ku @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14Understand this errorAI
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
_flushOutcomes @ baseclient.ts:912
(anonymous) @ client.ts:87Understand this errorAI
log.ts:11 [d2-stores] Profile from Bungie.net is is 1.987s old, while the cached profile is 40.808s old. Using the new profile from Bungie.net.
log.ts:59 [d2-stores] Process inventory: 40.349853515625 ms
log.ts:59 [d2-stores] Inventory state update: 12.3349609375 ms
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
_flushOutcomes @ baseclient.ts:912
(anonymous) @ client.ts:87Understand this errorAI
log.ts:11 [d2-stores] Profile from Bungie.net is is 1.216s old, while the cached profile is 124.963s old. Using the new profile from Bungie.net.
log.ts:59 [d2-stores] Process inventory: 48.178955078125 ms
log.ts:59 [d2-stores] Inventory state update: 10.578857421875 ms
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
_flushOutcomes @ baseclient.ts:912
(anonymous) @ client.ts:87Understand this errorAI
log.ts:11 [d2-stores] Profile from Bungie.net is is 18.031s old, which is the same age as the cached profile. Skipping update.
fetch.ts:51 
        
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7&sentry_client=sentry.javascript.react%2F8.40.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:51
(anonymous) @ base.ts:76
add @ promisebuffer.ts:49
send @ base.ts:92
sendEnvelope @ baseclient.ts:557
_flushOutcomes @ baseclient.ts:912
(anonymous) @ client.ts:87Understand this errorAI
log.ts:11 [d2-stores] Profile from Bungie.net is is 1.357s old, while the cached profile is 38.405s old. Using the new profile from Bungie.net.
log.ts:59 [d2-stores] Process inventory: 54.409912109375 ms
log.ts:59 [d2-stores] Inventory state update: 11.051025390625 ms
```

**Comment by bhollis** [comment]
There isn't any wish list (or any file at all) at the path  https://raw.githubusercontent.com/The-Dreamz/DIM-Wishlist/refs/heads/main/Dawning%20Wish%20List%20-%20Newest.txt?token=GHSAT0AAAAAAC3ZHTKZMDVBEUF4R7P2WIMQZ22COPA - can you help me understand what you expect to happen here?
