### ISSUE TITLE
Sheet has unexpected bottom offset in Opera

### ISSUE THREAD

**Issue by TeHeS13** [DestinyItemManager/DIM#10877]
### DIM Version

Версия 8.52.0 (release), собрана 23.12.2024, 07:20:12

### Browser Details

Opera 115.0.0.0

### OS Details

Windows 10 Debug

### Describe the bug

When opening a card for any item with a lot of description (perks, desirable rolls, etc.), the content partially extends beyond the top border of the card, which makes it impossible to follow some links associated with this item (for example Light.gg)
![Opera Снимок_2024-12-29_122010_app destinyitemmanager com](https://github.com/user-attachments/assets/21fc88e9-e8b3-4852-a0db-baa458cdc78d)

P.S. For some reason, the site in the OS Details item indicates Windows 10, although Windows 11 is installed
P.S.S. Also, for some reason, DIM Sync Error began to appear frequently, but as noted, this is not so critical and does not affect the main operation of the service.

### Logs

```shell
[app] DIM v8.52.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Either the 'unsafe-inline' keyword, a hash ('sha256-kPx0AsF0oz2kKiZ875xSvv693TBHkQ/0SkMJZnnNpnQ='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ chrome-extension://b…f/includes/tab.js:1
8140-93ee3186.js:2 [d2-stores] Loaded cached profile from IndexedDB, using it until new data is available. It is 47376.553s old.
8140-93ee3186.js:2 [bungie auth] Successfully updated auth token from refresh token.
8140-93ee3186.js:2 [dim sync] globalSettings Object
8140-93ee3186.js:2 [dim sync] Loaded profile from DIM API Object
8140-93ee3186.js:2 [dim sync] Saving profile data to IDB
3059-b0c6c418.js:1 [manifest] Load manifest: 15132.980224609375 ms
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 0.914s old, while the cached profile is 47391.617s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 421.288818359375 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 45.85595703125 ms
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 3.787s old, which is the same age as the cached profile. Skipping update.
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 3.803s old, which is the same age as the cached profile. Skipping update.
8140-93ee3186.js:2 [applySocketOverrides] Tried to override to a socket that didn't exist in the options 489506521 Array(1)
(anonymous) @ 8140-93ee3186.js:2
3059-b0c6c418.js:1 [hashLookupFailure] DestinyInventoryItemDefinition[261001205]
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is -0.529s old, while the cached profile is 125.769s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 94.14794921875 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 37.4638671875 ms
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 117.503s old, which is the same age as the cached profile. Skipping update.
5025-d6015cc2.js:2 Unrecognized Content-Security-Policy directive 'prefetch-src'.
cl @ 5025-d6015cc2.js:2
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 10000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is -0.954s old, while the cached profile is 592.432s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 193.781982421875 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 89.39208984375 ms
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_NETWORK_IDLE_TIMEOUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 64612.68188976598 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 10000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is -1.829s old, while the cached profile is 42.882s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 96.22705078125 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 30.511962890625 ms
5025-d6015cc2.js:2 Unrecognized Content-Security-Policy directive 'prefetch-src'.
cl @ 5025-d6015cc2.js:2
banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89 Unrecognized Content-Security-Policy directive 'prefetch-src'.
OpenCollectiveWidget.inject @ banner.js?style={%22a%22:{%22display%22:%22none%22},%20%22h2%22:{%22color%22:%22white%22}}:89
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 13120.459394298756 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 209117.51338169823 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 107.704s old, which is the same age as the cached profile. Skipping update.
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is -1.257s old, while the cached profile is 228.764s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 86.416015625 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 36.674072265625 ms
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 20.453s old, which is the same age as the cached profile. Skipping update.
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
i @ 3059-b0c6c418.js:1
(anonymous) @ main-d360028c.js:1
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is -1.836s old, while the cached profile is 39.241s old. Using the new profile from Bungie.net.
3059-b0c6c418.js:1 [d2-stores] Process inventory: 105.47607421875 ms
3059-b0c6c418.js:1 [d2-stores] Inventory state update: 36.51806640625 ms
478Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
i @ 3059-b0c6c418.js:1
(anonymous) @ main-d360028c.js:1
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
8140-93ee3186.js:2 [d2-stores] Profile from Bungie.net is is 39.444s old, which is the same age as the cached profile. Skipping update.
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_TIMED_OUT
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
i @ 3059-b0c6c418.js:1
(anonymous) @ main-d360028c.js:1
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
api.destinyitemmanager.com/profile?platformMembershipId=4611686018523873128&destinyVersion=2&components=settings%2Cloadouts%2Ctags%2Chashtags%2Csearches%2Ctriumphs:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
8140-93ee3186.js:2 [dim sync] Unable to get profile from DIM API TypeError: Failed to fetch
    at 8140-93ee3186.js:2:80315
    at l (main-d360028c.js:1:109796)
(anonymous) @ 8140-93ee3186.js:2
i @ 3059-b0c6c418.js:1
(anonymous) @ main-d360028c.js:1
8140-93ee3186.js:2 [dim sync] Waiting 600000 ms before re-attempting profile fetch
```

**Comment by bhollis** [comment]
The sheet containing the Armory information is meant to be attached to the bottom of the window - the bug is that it's shifted up. Could you try another browser, in case it's a problem specific to Opera or the addons you have installed?

**Comment by TeHeS13** [comment]
> The sheet containing the Armory information is meant to be attached to the bottom of the window - the bug is that it's shifted up. Could you try another browser, in case it's a problem specific to Opera or the addons you have installed?

At your request, I tried to check this on other browsers:
(This took a very long time, because both browsers took a VERY long time to load pages, giving ERR_CONNECTION_RESET errors when loading the main welcome page)

- For Google Chrome: Everything loaded. No bug was found. The DIM Sync error appeared for a while and quickly disappeared. The inventory loaded as slowly as on Opera GX.
- For Microsoft Edge: Everything loaded and works stably. No bug was found yet. There was also no DIM Sync error, which is also good. The inventory loaded incredibly quickly.

P.S.
I also forgot to mention last time that if you reduce the size of the browser window, the lower offset becomes even larger, almost completely hiding the Armory information.
For some reason I can't reproduce the bug on Opera GX right now. Although the first page refresh today did catch the bug, I'm a fool and refreshed the page again, but it didn't happen anymore. But yesterday page refreshes didn't affect the bug. It was there and nothing changed.

**Comment by bhollis** [comment]
Gotcha. In my experience Opera GX is a very buggy version of Chrome, so if you can use another browser that's great. I don't know if the problem is Opera itself or an addon you have installed on it.
