### ISSUE TITLE
Don't allow equipping items that require too high a level

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#2598]
We probably shouldn't allow you to equip an item that requires a higher level, at all, rather than firing an error as we do now. Although it might be more frustrating to just not be able to drop it (or to have a missing equip button) and not know why?

https://sentry.io/destiny-item-manager/dim/issues/444024370/

```
Error: Cela ne peut être équipé que par les personnages de niveau 24 ou plus.
  at resolver (./src/app/inventory/dimItemService.factory.ts:715:16)
  at canEquip (./src/app/inventory/dimItemService.factory.ts:705:11)
  at isValidTransfer (./src/app/inventory/dimItemService.factory.ts:728:29)
  at moveTo (./src/app/inventory/dimItemService.factory.ts:750:11)
  at fn (./src/app/inventory/dimStoreBucket.directive.js:155:40)
...
(8 additional frame(s) were not displayed)
```

**Comment by delphiactual** [comment]
Possibly closed by Shadowkeep
