### ISSUE TITLE
ReferenceError: 'indexedDB' is not defined

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#2853]
https://sentry.io/destiny-item-manager/dim/issues/564616288/

```
ReferenceError: 'indexedDB' is not defined
  at prototype.get (./src/app/storage/indexed-db-storage.ts:14:5)
  at Anonymous function (./src/app/storage/sync.service.ts:194:11)
  at Generator.prototype.next (/)
  at Anonymous function (./src/app/storage/sync.service.ts:179:5)
  at Generator.prototype.next (/)
...
(18 additional frame(s) were not displayed)
```

https://github.com/axemclion/IndexedDBShim

**Comment by delphiactual** [comment]
browserlist:
"last 2 Edge versions"

this error was reported on the current release of Edge

**Comment by bhollis** [comment]
https://caniuse.com/#feat=indexeddb

This suggests Edge supports IndexedDB. We aren’t using web workers.
