### ISSUE TITLE
DIM Can't store data (DIM Beta 12/26/21)

### ISSUE THREAD

**Issue by darkelement1987** [DestinyItemManager/DIM#7557]
### DIM Version

BETA

### Browser Details

Chrome 96.0.4664.110

### OS Details

Windows 10 Version 10.0.19042.1288

### Describe the bug

![image](https://user-images.githubusercontent.com/21128187/147402347-0f48da7e-059f-4f4d-93f3-631515be44b4.png)

I've tried:

- Clearing browser cache
- Checked HD space 2gb+ free space
- Browsing in normal mode

DIM Beta worked fine yesterday.

### Logs

```shell
Language Detected: nl-nl
instrument.ts:130 Language Assigned: en
instrument.ts:130 [dim sync] globalSettings Object
instrument.ts:130 [accounts] Unable to load accounts from IDB DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499132
    at new Promise (<anonymous>)
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499101
    at async https://beta.destinyitemmanager.com/main-8b3f99.js:1:79620
    at async https://beta.destinyitemmanager.com/855-d24a36.js:1:8880
    at async https://beta.destinyitemmanager.com/main-8b3f99.js:1:79765
    at async https://beta.destinyitemmanager.com/855-d24a36.js:1:8880
(anonymous) @ instrument.ts:130
instrument.ts:130 [app] DIM v6.96.0.1001068 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:130 [storage] Failed Storage Test DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499132
    at new Promise (<anonymous>)
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499101
    at async https://beta.destinyitemmanager.com/main-8b3f99.js:1:71051
(anonymous) @ instrument.ts:130
idb-keyval.ts:43 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499132
    at new Promise (<anonymous>)
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499101
    at async https://beta.destinyitemmanager.com/main-8b3f99.js:1:110530
    at async https://beta.destinyitemmanager.com/main-8b3f99.js:1:110426
idb-keyval.ts:43 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499132
    at new Promise (<anonymous>)
    at https://beta.destinyitemmanager.com/main-8b3f99.js:1:499101
```

**Comment by bhollis** [comment]
I wonder if we need to try and detect this and delete/recreate the keyval store

**Comment by nev-r** [comment]
probably, just. not sure how to purposely corrupt my db

**Comment by nev-r** [comment]
you likely need to nuke your database, it seems inaccessible
![image](https://user-images.githubusercontent.com/68782081/147466252-2d0c64d3-7443-40dd-966b-63e11cb442b1.png)

**Comment by darkelement1987** [comment]
> you likely need to nuke your database, it seems inaccessible ![image](https://user-images.githubusercontent.com/68782081/147466252-2d0c64d3-7443-40dd-966b-63e11cb442b1.png)

Thanks, that solved my problem.

**Comment by bhollis** [comment]
I wonder how we could distinguish this error
