### ISSUE TITLE
Mass transferring items to my vault using a search doesn't work

### ISSUE THREAD

**Issue by robdquick37** [DestinyItemManager/DIM#7686]
### DIM Version

Dim Beta Version 6.98.0.1001159 (beta)

### Browser Details

MS Edge Version 97.0.1072.55 (Official build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Trying to move any set of items that have been filtered using the search bar to my vault results in the error as shown above. This happens when I do the search, then click on the Vault icon at the top and then click 'Transfer Search'

I've tried multiple different searches, including ones with multiple parts ((is:armor or is:weapon) -is:equipped is:incurrentchar) and even just single items (name:"crimson")

Using these same searches I can move items between my characters just fine, the error only occurs when trying to move items to my vault.

I can click on an individual piece of armour or a weapon and click the 'Vault' button that appears next to it and it moves fine, so it specifically seems to be an error with the search and the Vault 'transfer search' button.

Using Dim Beta Version 6.98.0.1001159 (beta), built on 08/01/2022, 00:57:50 in MS Edge Version 97.0.1072.55 (Official build) (64-bit) and Chrome Version 96.0.4664.110 (Official Build) (64-bit)

If you need any other details please let me know!

Have also posted to reddit: https://www.reddit.com/r/DestinyItemManager/comments/ryzd3r/mass_transferring_items_to_my_vault_using_a/

### Logs

```shell
DevTools failed to load source map: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
instrument.ts:130 Language Detected: en-gb
instrument.ts:130 Language Assigned: en
instrument.ts:130 [app] DIM v6.98.0.1001159 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
fetch.ts:72 
        
       POST https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:72
t @ syncpromise.ts:34
(anonymous) @ fetch.ts:71
t.add @ promisebuffer.ts:34
e._sendRequest @ fetch.ts:69
e.sendSession @ fetch.ts:31
t.sendSession @ basebackend.ts:108
t._sendSession @ baseclient.ts:285
t.captureSession @ baseclient.ts:181
t._sendSessionUpdate @ hub.ts:471
t.captureSession @ hub.ts:411
(anonymous) @ sdk.ts:226
(anonymous) @ sdk.ts:98
Mt @ sdk.ts:18
39515 @ exceptions.ts:125
s @ bootstrap:19
2914 @ main-2aec3d.js:1
s @ bootstrap:19
82823 @ main-2aec3d.js:1
s @ bootstrap:19
81347 @ main-2aec3d.js:1
s @ bootstrap:19
899 @ main-2aec3d.js:1
s @ bootstrap:19
74522 @ main-2aec3d.js:1
s @ bootstrap:19
(anonymous) @ main-2aec3d.js:1
s.O @ chunk loaded:23
(anonymous) @ main-2aec3d.js:1
t @ jsonp chunk loading:71
(anonymous) @ main-2aec3d.js:1
google.js:14 
        
       GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
74522 @ google.js:14
s @ bootstrap:19
(anonymous) @ main-2aec3d.js:1
s.O @ chunk loaded:23
(anonymous) @ main-2aec3d.js:1
t @ jsonp chunk loading:71
(anonymous) @ main-2aec3d.js:1
instrument.ts:130 [dim sync] globalSettings {dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, …}
log.ts:44 Load manifest: 1061.634033203125 ms
instrument.ts:130 [dim sync] Saving profile data to IDB
log.ts:44 Process inventory: 76.968994140625 ms
log.ts:44 Inventory state update: 980.10400390625 ms
inventory:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
log.ts:44 Process inventory: 61.81298828125 ms
log.ts:44 Inventory state update: 100.755126953125 ms
instrument.ts:130 [loadout] Apply loadout Filtered Items to Vault
instrument.ts:130 
        
       [loadout] failed loadout {phase: 0, equipNotPossible: false, itemStates: {…}, socketOverrideStates: {…}, modStates: Array(0)} TypeError: Cannot read properties of undefined (reading 'plugs')
    at selectors.ts:227:79
    at index.js:67:25
    at h (defaultMemoize.js:123:20)
    at index.js:81:40
    at h (defaultMemoize.js:123:20)
    at loadout-apply.ts:200:36
    at index.js:16:18
    at dispatch (redux.js:659:28)
    at loadout-apply.ts:108:7
    at action-queue.ts:13:21
(anonymous) @ instrument.ts:130
s @ log.ts:33
(anonymous) @ loadout-apply.ts:128
await in (anonymous) (async)
(anonymous) @ index.js:16
onClick @ LoadoutPopup.tsx:197
Be @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Tr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$o @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
r @ helpers.ts:88
log.ts:44 Loadout Application: 18.247802734375 ms
instrument.ts:130 [dim sync] Saving profile data to IDB
log.ts:44 prepareUpdateQueue: 0.401123046875 ms
instrument.ts:130 [flushUpdates] Flushing queue of 1 updates
instrument.ts:130 [flushUpdates] got results [{…}] [{…}]
instrument.ts:130 [dim sync] Saving profile data to IDB
```

**Comment by robdquick37** [comment]
Just realised this is the same issue as https://github.com/DestinyItemManager/DIM/issues/7678 So this can be merged or closed.
