### ISSUE TITLE
S is not iterable error

### ISSUE THREAD

**Issue by ABzy128** [DestinyItemManager/DIM#7914]
### DIM Version

Version 7.5.1.1001312 (beta), built on 2/19/2022, 6:25:40 PM

### Browser Details

Version 98.0.4758.102 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

I opened the loadout menu in the inventory menu, then opened the fashion menu. I tried to clean up fashion items, so fashion is unchanged when I change my loadout. However, there is an error when I press the "Clear Fashion" button and then save the whole loadout. I checked it with individual clear buttons for ornaments and shaders, and only the clear shaders button causes the crash. However, removing shaders by pressing "x" does not cause any issues.

### Logs

```shell
TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691)
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 [DIM Code] TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691) Object
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691)
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 [DIM Code] TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691) Object
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691)
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 [DIM Code] TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691) Object
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691)
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 [DIM Code] TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691) Object
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691)
(anonymous) @ 358-3fd23f.js:2
358-3fd23f.js:2 [DIM Code] TypeError: s is not iterable
    at u (main-a326aa.js:1:438032)
    at aa (779-62304b.js:2:329772)
    at Wa (779-62304b.js:2:339290)
    at $s (779-62304b.js:2:382793)
    at Tu (779-62304b.js:2:369093)
    at Ou (779-62304b.js:2:369021)
    at ku (779-62304b.js:2:368884)
    at mu (779-62304b.js:2:365871)
    at 779-62304b.js:2:315694
    at t.unstable_runWithPriority (779-62304b.js:2:453891)
    at $i (779-62304b.js:2:315471)
    at Ki (779-62304b.js:2:315639)
    at qi (779-62304b.js:2:315574)
    at Me (779-62304b.js:2:386338)
    at Yt (779-62304b.js:2:294262)
    at HTMLBodyElement.i (358-3fd23f.js:2:44691) Object
```

**Comment by ryan-rushton** [comment]
Should be fixed now

**Comment by nev-r** [comment]
thank you very much for the fast report! if you accept the next update, it should be fixed now.
