### ISSUE TITLE
Some of our rich text objective hashes don't exist anymore

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7956]
https://sentry.io/organizations/destiny-item-manager/issues/3038164432/?referrer=github_plugin

```
HashLookupFailure: hashLookupFailure: DestinyObjectiveDefinition[557968429]
  at r (./src/app/destiny2/definitions.ts:15:5)
  at get (./src/app/destiny2/d2-definitions.ts:194:44)
  at None (./src/app/dim-ui/rich-destiny-text.ts:99:26)
  at asyncFunctionResume ([native code])
  at apply (./src/app/dim-ui/rich-destiny-text.ts:122:37)
...
(6 additional frame(s) were not displayed)
```

**Comment by delphiactual** [comment]
#7945
