### ISSUE TITLE
Error loading shared loadout

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7957]
https://sentry.io/organizations/destiny-item-manager/issues/3045417547/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'findIndex')
  at None (/main-29b474.js:1:316917)
  at None (/509-2cac3c.js:1:2726)
  at r.exports (/509-2cac3c.js:1:762)
  at None (/509-2cac3c.js:1:2702)
  at None (/509-2cac3c.js:1:2272)
...
(31 additional frame(s) were not displayed)
```

**Comment by bhollis** [comment]
This was on a super old version
