### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7958]
https://sentry.io/organizations/destiny-item-manager/issues/3038010987/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'data')
  at getCraftableInfo (./src/app/records/presentation-nodes.ts:421:44)
  at toCraftable (./src/app/records/presentation-nodes.ts:371:16)
  at None (./src/app/records/presentation-nodes.ts:354:7)
  at Array.map (<anonymous>)
  at toCraftables (./src/app/records/presentation-nodes.ts:353:63)
...
(27 additional frame(s) were not displayed)
```

**Comment by nev-r** [comment]
ppppprobably fixed already in beta
