### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.metricComponent.objectiveProgress.complete')

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7962]
https://sentry.io/organizations/destiny-item-manager/issues/3038023011/?referrer=github_plugin

```
TypeError: undefined is not an object (evaluating 'e.metricComponent.objectiveProgress.complete')
  at predicate (./src/app/records/presentation-nodes.ts:135:70)
  at iteratee (./src/app/utils/util.ts:10:35)
  at count (./src/app/utils/util.ts:10:10)
  at toPresentationNodeTree (./src/app/records/presentation-nodes.ts:135:22)
  at toPresentationNodeTree (./src/app/records/presentation-nodes.ts:148:23)
...
(19 additional frame(s) were not displayed)
```

**Comment by justrealmilk** [comment]
This is probably redacted metrics. I had the same issue
