### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sort')

### ISSUE THREAD

**Issue by Scarcesss** [DestinyItemManager/DIM#7967]
Hi, since few months I'm facing this error message " Something went wrongTypeError Cannot read properties of undefined (reading 'sort') for one of my charracters when I try to reach the loadouts page (for the titan).
It works perfectly for my hunter and warlock.
From what does it come from?
Thank you in advance.
Clem

**Comment by ryan-rushton** [comment]
Hi @Scarcesss, can you please get the browser logs when this happens for you? To open them in chrome you want to click on the following option in the view menu.

<img width="655" alt="Screen Shot 2022-02-27 at 1 10 45 pm" src="https://user-images.githubusercontent.com/7344652/155866588-fbf98b6b-9adf-414c-8189-44fb7f5b5402.png">

**Comment by bhollis** [comment]
Can you also let us know what version of DIM you're on? From the About DIM page.

**Comment by bhollis** [comment]
I'm afraid this bug report doesn't have enough information for us to do anything with it. Please re-file using our bug report template and fill out all the information it asks for.

**Comment by Scarcesss** [comment]
Hi, 
This is the error :
TypeError: Cannot read properties of undefined (reading 'sort')
    at LoadoutView.tsx:95:73
    at _arrayAggregator.js:17:32
    at _createAggregator.js:19:12
    at U (LoadoutView.tsx:95:22)
    at aa (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Tu (react-dom.production.min.js:250:347)
    at Ou (react-dom.production.min.js:250:278)
    at ku (react-dom.production.min.js:250:138)
    at mu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at scheduler.production.min.js:18:343
    at $i (react-dom.production.min.js:122:325)
    at Ki (react-dom.production.min.js:123:61)
    at qi (react-dom.production.min.js:122:428)
    at gu (react-dom.production.min.js:244:190)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at i (Subscription.js:90:20)
    at g (redux.js:296:32)
    at index.js:20:16
    at dispatch (redux.js:659:28)
    at d2-stores.ts:233:9

**Comment by Scarcesss** [comment]
DIM version I'm using is v7.7.0

**Comment by Scarcesss** [comment]
Sorry for the late answer, can you please reopen the topic? Thanks ;)
