### ISSUE TITLE
Classified items get classed as titan when using 'is:maxpower'

### ISSUE THREAD

**Issue by mt025** [DestinyItemManager/DIM#8099]
### DIM Version

Version 7.8.0.1001465 (beta), built on 08/03/2022, 08:25:30

### Browser Details

Firefox Beta 98.0 (64-Bit)

### OS Details

Windows 10 21H2

### Describe the bug

When using `is:maxpower`, any classified items will count for titan, even if they are from other classes. The classified items in the screenshot below are all hunter items.

![Is max power shown, classifed items show as max power](https://user-images.githubusercontent.com/2631330/157285703-7ee13564-918d-4d2d-94f0-155666285a87.png)

### Logs

```shell
Content Security Policy: Couldn't process unknown directive 'prefetch-src' 2
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). moz-extension:1:5003
[app] DIM v7.8.0.1001465 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues instrument.ts:125:32
Language Detected: en-gb instrument.ts:125:32
Language Assigned: en instrument.ts:125:32
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/279673/envelope/?sentry_key=1367619d45da481b8148dd345c1a1330&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).
Error: Could not establish connection. Receiving end does not exist. broadcastStatus.ts:3:4
[dim sync] globalSettings 
Object { dimApiEnabled: true, destinyProfileMinimumRefreshInterval: 15, destinyProfileRefreshInterval: 30, autoRefresh: false, refreshProfileOnVisible: true, bustProfileCacheOnHardRefresh: false, dimProfileMinimumRefreshInterval: 300, showIssueBanner: false }
instrument.ts:125:32
Cookie “__cflb” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 2 LinkedProfiles
Cookie “__cflb” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 4611686018490516086
[dim sync] Saving profile data to IDB instrument.ts:125:32
Load manifest: 6331ms - timer ended log.ts:58:23
Cookie “__cflb” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 4611686018490516086
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
Process inventory: 193ms - timer ended log.ts:58:23
Inventory state update: 929ms - timer ended log.ts:58:23
Cookie “__cflb” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. 2 4611686018490516086
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
[d2-stores] Missing Item Definition:

 
Object { item: {…}, itemDef: {…}, instanceDef: {…} }
 

This item is not in the current manifest and will be added at a later time by Bungie. instrument.ts:125:32
Process inventory: 153ms - timer ended log.ts:58:23
Inventory state update: 165ms - timer ended log.ts:58:23
[dim sync] Saving profile data to IDB instrument.ts:125:32
prepareUpdateQueue: 1ms - timer ended log.ts:58:23
[flushUpdates] Flushing queue of 1 updates instrument.ts:125:32
[flushUpdates] got results 
Array [ {…} ]
 
Array [ {…} ]
instrument.ts:125:32
[dim sync] Saving profile data to IDB instrument.ts:125:32
```

**Comment by mt025** [comment]
`is:maxpowerloadout` produces the correct result

**Comment by nev-r** [comment]
hi, this should be fixed once you accept the most recent beta update, let us know if it looks right

**Comment by mt025** [comment]
Looks good, however the items in question were declassifed 5 minutes after the merge and 50 minutes before your message so I was unable to check. I will keep my eye out when I aquire more classifed items. Thanks!

**Comment by nev-r** [comment]
HAH. sorry. thank you for the report though, should be good next time.
