### ISSUE TITLE
Something went wrong. S in not iterable.

### ISSUE THREAD

**Issue by AdamHuli** [DestinyItemManager/DIM#8557]
### DIM Version

orange

### Browser Details

Chrome 103.0.5060.114

### OS Details

Windows 10

### Describe the bug

Every time I open DIM, I see: Something went wrongTypeError, s is not iterable. I tried to log out log in but it doesnt work. Can anyone help me fix this? Thanks

### Logs

```shell
[app] DIM v7.24.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:123 Language Detected: cs-cz
instrument.ts:123 Language Assigned: en
instrument.ts:123 [dim sync] globalSettings Object
log.ts:58 Load manifest: 2219.44189453125 ms
instrument.ts:123 TypeError: s is not iterable
    at Object.suggestionsGenerator (freeform.tsx:87:37)
    at search-config.ts:71:39
    at index.js:67:25
    at h (defaultMemoize.js:123:20)
    at index.js:81:40
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at redux-utils.ts:52:46
    at t (with-selector.production.min.js:11:204)
    at with-selector.production.min.js:11:420
    at Object.Po [as useSyncExternalStore] (react-dom.production.min.js:173:35)
    at t.useSyncExternalStore (react.production.min.js:25:469)
    at e.useSyncExternalStoreWithSelector (with-selector.production.min.js:11:489)
    at useSelector.js:41:27
    at Hn (Compare.tsx:68:27)
    at Eo (react-dom.production.min.js:167:137)
    at Rs (react-dom.production.min.js:197:258)
    at wl (react-dom.production.min.js:292:88)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 [DIM Code] TypeError: s is not iterable
    at Object.suggestionsGenerator (freeform.tsx:87:37)
    at search-config.ts:71:39
    at index.js:67:25
    at h (defaultMemoize.js:123:20)
    at index.js:81:40
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at redux-utils.ts:52:46
    at t (with-selector.production.min.js:11:204)
    at with-selector.production.min.js:11:420
    at Object.Po [as useSyncExternalStore] (react-dom.production.min.js:173:35)
    at t.useSyncExternalStore (react.production.min.js:25:469)
    at e.useSyncExternalStoreWithSelector (with-selector.production.min.js:11:489)
    at useSelector.js:41:27
    at Hn (Compare.tsx:68:27)
    at Eo (react-dom.production.min.js:167:137)
    at Rs (react-dom.production.min.js:197:258)
    at wl (react-dom.production.min.js:292:88)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 TypeError: s is not iterable
    at Object.suggestionsGenerator (freeform.tsx:87:37)
    at search-config.ts:71:39
    at index.js:67:25
    at h (defaultMemoize.js:123:20)
    at index.js:81:40
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at t (with-selector.production.min.js:11:311)
    at with-selector.production.min.js:11:420
    at Object.Po [as useSyncExternalStore] (react-dom.production.min.js:173:35)
    at t.useSyncExternalStore (react.production.min.js:25:469)
    at e.useSyncExternalStoreWithSelector (with-selector.production.min.js:11:489)
    at useSelector.js:41:27
    at ds (InfusionFinder.tsx:129:19)
    at Eo (react-dom.production.min.js:167:137)
    at Rs (react-dom.production.min.js:197:258)
    at wl (react-dom.production.min.js:292:88)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 [DIM Code] TypeError: s is not iterable
    at Object.suggestionsGenerator (freeform.tsx:87:37)
    at search-config.ts:71:39
    at index.js:67:25
    at h (defaultMemoize.js:123:20)
    at index.js:81:40
    at h (defaultMemoize.js:123:20)
    at index.js:77:37
    at h (defaultMemoize.js:123:20)
    at t (with-selector.production.min.js:11:311)
    at with-selector.production.min.js:11:420
    at Object.Po [as useSyncExternalStore] (react-dom.production.min.js:173:35)
    at t.useSyncExternalStore (react.production.min.js:25:469)
    at e.useSyncExternalStoreWithSelector (with-selector.production.min.js:11:489)
    at useSelector.js:41:27
    at ds (InfusionFinder.tsx:129:19)
    at Eo (react-dom.production.min.js:167:137)
    at Rs (react-dom.production.min.js:197:258)
    at wl (react-dom.production.min.js:292:88)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 [dim sync] Saving profile data to IDB
instrument.ts:123 [d2-stores] Error processing item Object TypeError: Cannot read properties of undefined (reading 'name')
    at R (d2-item-factory.ts:290:35)
    at L (d2-item-factory.ts:96:21)
    at d2-stores.ts:386:26
    at d2-stores.ts:311:5
    at Array.map (<anonymous>)
    at d2-stores.ts:310:63
    at d2-stores.ts:212:24
(anonymous) @ instrument.ts:123
instrument.ts:123 [d2-stores] Error loading stores TypeError: Cannot read properties of undefined (reading 'name')
    at L (d2-item-factory.ts:136:55)
    at d2-stores.ts:386:26
    at d2-stores.ts:311:5
    at Array.map (<anonymous>)
    at d2-stores.ts:310:63
    at d2-stores.ts:212:24
(anonymous) @ instrument.ts:123
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Comment by bhollis** [comment]
Check out https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting. It seems you have a corrupted manifest and need to clear your cache.

**Comment by AdamHuli** [comment]
> Check out https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting. It seems you have a corrupted manifest and need to clear your cache.

thanks, it worked
