### ISSUE TITLE
Mods Not Working

### ISSUE THREAD

**Issue by Jkl1013** [DestinyItemManager/DIM#8615]
### DIM Version

Version 7.28.0 (release), built on 7/31/2022, 11:35:11 PM

### Browser Details

Microsoft Edge Version 103.0.1264.77 (Official build) (64-bit)

### OS Details

Windows 11

### Describe the bug

When i go and try and make a build in Destiny Item Manager, i try and put the Radiant Light and Powerful Friends Mods in and it keeps bringing up an Error Box that says that they couldn't find know where to place the mods.

### Logs

```shell
[app] DIM v7.28.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:123 Language Detected: en-us
instrument.ts:123 Language Assigned: en
instrument.ts:123 [dim sync] globalSettings Object
log.ts:58 Load manifest: 1117.819091796875 ms
instrument.ts:123 [dim sync] Saving profile data to IDB
log.ts:58 Process inventory: 86.454345703125 ms
log.ts:58 Inventory state update: 9.041015625 ms
/4611686018442676984/d2/inventory:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
log.ts:58 Process inventory: 65.5009765625 ms
log.ts:58 Inventory state update: 13.02197265625 ms
​ [loadout optimizer] Processing 21942690 combinations from 276 items [object Object]
​ [loadout optimizer] found 462947 stat mixes after processing 21942690 stat combinations in 967.3999999761581 ms -  22682127 combos/s [object Object] [object Object]
instrument.ts:123 [loadout optimizer] useProcess: worker time 991.9000000059605ms
instrument.ts:123 [loadout optimizer] useProcess 997.2000000178814ms
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Radiant Light (2979815167)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Radiant Light (2979815167)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:123
instrument.ts:123 
        
       [DIM Code] Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at m (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 Object
```

**Comment by robojumper** [comment]
@Jkl1013 can you try if this works on Beta DIM at https://beta.destinyitemmanager.com and report back? I think this should be fixed with #8476 which made it into Beta and should hit app.dim in a few days.

**Comment by Jkl1013** [comment]
I actually tried the beta right before I made this post, it did the same thing

**Comment by robojumper** [comment]
Can you please include a crash log from beta that confirms the beta version is `DIM v7.28.0.1001905 (beta)`, and also scroll down on the Beta DIM settings page, click "Export API profile response", and upload that file here? That should allow me to reproduce the issue. Thanks!

**Comment by Jkl1013** [comment]
[app] DIM v7.28.0.1001905 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:123 Language Detected: en-us
instrument.ts:123 Language Assigned: en
instrument.ts:123 [dim sync] globalSettings Object
log.ts:58 Load manifest: 1299.0771484375 ms
instrument.ts:123 [dim sync] Saving profile data to IDB
log.ts:58 Process inventory: 87.051025390625 ms
log.ts:58 Inventory state update: 8.450927734375 ms
/4611686018442676984/d2/inventory:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
​ [loadout optimizer] Processing 21942690 combinations from 276 items [object Object]
​ [loadout optimizer] found 462947 stat mixes after processing 21942690 stat combinations in 996.4000000059605 ms -  22021969 combos/s [object Object] [object Object]
instrument.ts:123 [loadout optimizer] useProcess: worker time 1021ms
instrument.ts:123 [loadout optimizer] useProcess 1026.7000000178814ms
instrument.ts:123 
        
       Error: We couldn't find anywhere to plug the mod Powerful Friends (1484685887)
    at C (mod-assignment-utils.ts:462:13)
    at u (Sockets.tsx:47:23)
    at Eo (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at _u (react-dom.production.min.js:280:389)
    at mu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Fa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

**Comment by Jkl1013** [comment]
It says it doesnt support the file type

**Comment by Jkl1013** [comment]
[profile-data.zip](https://github.com/DestinyItemManager/DIM/files/9271476/profile-data.zip)

**Comment by robojumper** [comment]
Thanks, I can reproduce the issue. In the meantime you can work around that bug by dismantling your blue class items, I think.
