### ISSUE TITLE
Primary Bows overview tab doesn't populate at first

### ISSUE THREAD

**Issue by zarbusiness** [DestinyItemManager/DIM#8793]
### DIM Version

Version 7.39.1.1002038 (beta), built on 10/20/2022, 8:54:00 AM

### Browser Details

Chrome 106.0.0.0

### OS Details

Windows 10

### Describe the bug

In the Inventory tab, the primary ammo bow pop-up window doesn't populate the weapon perk rolls the same as other weapons. Normally, under the frame, shader, mod and masterwork row the perk rolls are displayed. Bows do not start with anything below the frame row. Clicking 'triage' and then 'overview' populates that space as normal. This does not happen on the Loadouts tab.

### Logs

```shell
instrument.ts:123 [app] DIM v7.39.1.1002038 (beta) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:123 Language Detected: en-us
instrument.ts:123 Language Assigned: en
instrument.ts:123 [dim sync] globalSettings Object
handle_data.js:78  Manifest parsed in: 249 ms
instrument.ts:123 [dim sync] Saving profile data to IDB
handle_data.js:395  User data parsed in: 11 ms
log.ts:58 Load manifest: 3307.146240234375 ms
handle_data.js:395  User data parsed in: 5 ms
log.ts:58 Process inventory: 108.81298828125 ms
log.ts:58 Inventory state update: 11.693115234375 ms
log.ts:58 Process inventory: 78.140869140625 ms
log.ts:58 Inventory state update: 13.02099609375 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A2852052802 Object
find_classNames.js:110 weapon_pressed
description.js:232 speed test 9000: 3.314208984375 ms
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A1399109800 Object
find_classNames.js:110 weapon_pressed
numbers.js:31 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at calculate (numbers.js:31:28)
    at numbers.js:23:71
    at Array.forEach (<anonymous>)
    at get_item_stats (numbers.js:12:25)
    at Wep_stats.calculate_stats (numbers.js:250:33)
    at add_stats (stats.js:78:10)
    at add_weapon_perks (description.js:9:5)
    at description.js:1:48
    at HTMLDivElement.<anonymous> (flow_handler.js:62:28)
instrument.ts:123 [clicked item] https://data.destinysets.com/i/InventoryItem%3A211938782 Object
find_classNames.js:110 weapon_pressed
description.js:4 Timer 'speed test 9000' already exists
add_weapon_perks @ description.js:4
numbers.js:31 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at calculate (numbers.js:31:28)
    at numbers.js:23:71
    at Array.forEach (<anonymous>)
    at get_item_stats (numbers.js:12:25)
    at Wep_stats.calculate_stats (numbers.js:250:33)
    at add_stats (stats.js:78:10)
    at add_weapon_perks (description.js:9:5)
    at description.js:1:48
    at HTMLDivElement.<anonymous> (flow_handler.js:62:28)
DevTools failed to load source map: Could not load content for chrome-extension://cjdnfmjmdligcpfcekfmenlhiopehjkd/node_modules/axios/dist/axios.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cjdnfmjmdligcpfcekfmenlhiopehjkd/node_modules/moment/min/moment.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by robojumper** [comment]
You're probably using the Clarity browser extension -- that's a known issue on their end.

**Comment by robojumper** [comment]
Ice-mourne/Clarity#19

**Comment by zarbusiness** [comment]
You're right, I am using Clarity. Thanks!
