### ISSUE TITLE
Beta - Loadout Optimizer - Something went wrong

### ISSUE THREAD

**Issue by Bimmr** [DestinyItemManager/DIM#9136]
### DIM Version

Version 7.58.0.1002311 (beta), built on 2/28/2023, 2:55:08 p.m.

### Browser Details

Edge 110.0.1587.57

### OS Details

Windows 10

### Describe the bug

1. Go to Loadouts
2. Go to Loadout Optimizer
3. Enable Add required stat mods
4. Set a Min for a stat

----
```
Something went wrong: TypeError
Cannot read properties of undefined (reading 'plug')
```

### Logs

```shell
instrument.ts:124 
        
       TypeError: Cannot read properties of undefined (reading 'plug')
    at I (mod-assignment-utils.ts:80:28)
    at S (mod-assignment-utils.ts:181:7)
    at GeneratedSet.tsx:89:52
    at Object.useMemo (react-dom.production.min.js:184:189)
    at t.useMemo (react.production.min.js:25:208)
    at Ht (GeneratedSet.tsx:84:28)
    at wa (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at bu (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at uu (react-dom.production.min.js:273:300)
    at Fi (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at ku (react-dom.production.min.js:281:398)
    at ou (react-dom.production.min.js:270:269)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.C (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124


instrument.ts:124 
     
       [DIM Code] TypeError: Cannot read properties of undefined (reading 'plug')
    at I (mod-assignment-utils.ts:80:28)
    at S (mod-assignment-utils.ts:181:7)
    at GeneratedSet.tsx:89:52
    at Object.useMemo (react-dom.production.min.js:184:189)
    at t.useMemo (react.production.min.js:25:208)
    at Ht (GeneratedSet.tsx:84:28)
    at wa (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:290:337)
    at bu (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at uu (react-dom.production.min.js:273:300)
    at Fi (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at ku (react-dom.production.min.js:281:398)
    at ou (react-dom.production.min.js:270:269)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.C (scheduler.production.min.js:14:128) Object
```

**Comment by bhollis** [comment]
Fixed by #9115
